-- Packages schema.
--
-- Deliberately plain SQL: text ids generated by the application rather than
-- gen_random_uuid(), no extensions, no partial indexes. The same statements
-- run against Postgres in production and against pg-mem in the test suite, so
-- the tests exercise the real queries rather than a second implementation.

create table if not exists users (
  id            text primary key,
  github_id     bigint not null unique,
  github_login  text not null,
  display_name  text,
  avatar_url    text,
  profile_url   text,
  created_at    timestamptz not null default now(),
  last_seen_at  timestamptz not null default now()
);

create index if not exists users_login_idx on users (github_login);

-- One row per signed-in browser. The cookie carries a random token; only its
-- sha256 is stored, so a dump of this table cannot be replayed as a login.
-- gh_token holds the OAuth access token encrypted with AES-256-GCM: it is
-- needed later to re-check repository permission, and it never leaves the
-- server.
create table if not exists sessions (
  id            text primary key,
  token_hash    text not null unique,
  user_id       text not null references users (id),
  gh_token      text,
  created_at    timestamptz not null default now(),
  expires_at    timestamptz not null
);

create index if not exists sessions_user_idx on sessions (user_id);

-- A cache of what the npm registry said, plus the identity this product adds.
-- Nothing here is computed or estimated: a null column means npm did not
-- report that field, and the front end renders a dash.
create table if not exists packages (
  name              text primary key,
  description       text,
  latest_version    text,
  license           text,
  homepage          text,
  repo_url          text,
  repo_owner        text,
  repo_name         text,
  keywords          jsonb not null default '[]',
  maintainers       jsonb not null default '[]',
  npm_created_at    timestamptz,
  npm_modified_at   timestamptz,
  version_count     int,
  fetched_at        timestamptz not null default now(),
  -- set only once a claim on this package reaches "verified"
  verified_owner_id text references users (id),
  verified_at       timestamptz,
  launched_at       timestamptz,
  identity_pda      text,
  identity_tx       text
);

create index if not exists packages_owner_idx on packages (verified_owner_id);
create index if not exists packages_launched_idx on packages (launched_at);

-- A developer's attempt to claim a package. The three proof columns are
-- independent and each records a fact that was checked, never an assumption.
-- See verify.js for the rule that turns them into a status.
create table if not exists claims (
  id                      text primary key,
  package_name            text not null references packages (name),
  user_id                 text not null references users (id),
  status                  text not null default 'pending',
  repo_control            boolean not null default false,
  repo_control_at         timestamptz,
  repo_permission         text,
  trusted_publisher       boolean not null default false,
  trusted_publisher_repo  text,
  publish_proof           boolean not null default false,
  publish_proof_version   text,
  publish_proof_at        timestamptz,
  maintainer_email_match  boolean not null default false,
  matched_maintainer      text,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now(),
  verified_at             timestamptz
);

create unique index if not exists claims_pkg_user_idx on claims (package_name, user_id);
create index if not exists claims_user_idx on claims (user_id);
create index if not exists claims_pkg_idx on claims (package_name);

-- Single-use nonces. kind is 'repo', 'npm_publish' or 'wallet'.
create table if not exists challenges (
  id            text primary key,
  kind          text not null,
  nonce         text not null,
  user_id       text not null references users (id),
  package_name  text,
  created_at    timestamptz not null default now(),
  expires_at    timestamptz not null,
  consumed_at   timestamptz
);

create index if not exists challenges_lookup_idx on challenges (user_id, kind, package_name);

create table if not exists wallets (
  id           text primary key,
  user_id      text not null references users (id),
  pubkey       text not null,
  cluster      text not null default 'devnet',
  verified_at  timestamptz not null default now()
);

create unique index if not exists wallets_user_pubkey_idx on wallets (user_id, pubkey);

-- Release history. Rows are append-only and never updated: a version that has
-- been published cannot change, so a second sighting of the same version is
-- ignored rather than overwritten.
create table if not exists releases (
  id            text primary key,
  package_name  text not null references packages (name),
  version       text not null,
  published_at  timestamptz,
  record_hash   text,
  onchain_tx    text,
  recorded_at   timestamptz not null default now()
);

create unique index if not exists releases_pkg_version_idx on releases (package_name, version);
create index if not exists releases_published_idx on releases (published_at);

-- The public activity feed. Only events the product itself caused are stored
-- here; npm release activity is read live from the registry instead, so it is
-- never a stale copy pretending to be current.
create table if not exists events (
  id            text primary key,
  kind          text not null,
  package_name  text,
  actor_login   text,
  payload       jsonb not null default '{}',
  created_at    timestamptz not null default now()
);

create index if not exists events_created_idx on events (created_at);
